### ISSUE TITLE
Google Earth Plugin

### ISSUE THREAD

**Issue by QIUWEIHAO** [stanford-gfx/Horus#3]
The only problem for setting up the environment based on instructions on https://github.com/stanford-gfx/Horus is the Google Earth Plugin for Chromium. The plugin is no longer exist on the official website. Without installing the plugin, the site localhost:5000 is stuck at the loading page. Could you please send me the way to install the plugin? or the plugin file?

**Comment by mikeroberts3000** [comment]
Ah, this is a bummer. I think it's currently impossible to install the Google Earth plugin. This plugin has been officially deprecated since 2015, and I think Google finally made it impossible to install.

If this was simply a matter of digging the installer file out of my downloads folder and sharing it with you, I would just include it (the installer file) on the Horus website. However, the procedure for installing the Google Earth plugin has always been to go to a particular website, and Chromium would install automagically install the plugin in the background.

Google has rolled a lot of the functionality that used to be in Google Earth, directly into Google Maps, and has presumably updated the Google Maps API accordingly. I would love to resurrect Horus, but I would need a student to take the lead on changing the web app to comply with the new Google Maps API. Once the web app is working again, there are a ton of interesting drone cinematography research problems to explore. Please do let me know if you're interested in taking this on.

**Comment by QIUWEIHAO** [comment]
Hi Mike,

I am really interested in doing this but I don’t know the workload for resurrect Horus, because I have not been familiar with your code yet.
I also would like to make this working on DJI products, which covers more consumers than 3dr. Besides 3dr gave up consumption market already.

Do you have any suggestions for resurrecting Horus?

Thank you,
Weihao

**Comment by mikeroberts3000** [comment]
We'd also love to get Horus working on DJI products. Have a look at the DJI documentation, and see if there is any sort of API for commanding DJI drones programatically. In other words, is there a way for me, as a programmer, to command a DJI drone to fly a particular trajectory, while pointing the camera how I want and recording video? If so, it should be pretty easy to get Horus working on DJI drones, and I'd be happy to work with you on getting this set up. Please do post your findings here.

**Comment by QIUWEIHAO** [comment]
Actually I have been working with DJI phantom 4 for couple of months for a simple art exhibition, and I get a Mavic Pro recently. Both products support programming with Mobile-SDK, which can be ran on iOS and Android. I also believe it should not be hard to make Horus working on DJI, given the control of camera and drone is programmable. 

How do you describe a trajectory? My idea is to export the trajectory in some format into a file. Then, let iOS program read the file and control the drone to fly. 

Could you also give me some advise for setting up Horus? Like make google maps api replace the google earth api.

**Comment by mikeroberts3000** [comment]
Very roughly speaking, we export trajectories as dense sequences of look-at and look-from points, uniformly sampled in time, at roughly 5Hz or so.

I think we export trajectories as npz files in Horus, because all of our code is in Python and we use numpy everywhere. But it would be easy to export in whatever format. So your high-level approach (i.e., Horus exports in whatever format, then there is an iOS app that imports and flies the DJI drone) sounds sensible. I bet this would be pretty easy to set up.

I don't know how the new Google Maps API works, so I can't advise you on that. Try to get a simple standalone web app working, where you're programmatically setting the camera pose (i.e., try to do some simple 3D camera animation using the new Google Maps API). There are probably tutorials you can follow. If you can get that working, then we should be able to hook up Horus to the new API without too much effort.

**Comment by gary-w-johnson** [comment]
Using the: 
http://sourceforge.net/projects/osxportableapps/files/Chromium/
(make sure to download ChromiumOSX_38.0.2125.122.dmg)

I was able to get it running on a mac book pro without locking up.

**Comment by mikeroberts3000** [comment]
@gary-w-johnson In addition to installing the right version of Chromium, were you also able to install the Google Earth plugin? When I navigate to https://www.google.com/earth/explore/products/plugin.html in Chromium, I no longer see the option of installing the Google Earth plugin. But that might be because I already have the plugin installed.

**Comment by gary-w-johnson** [comment]
Hi Mike, I still have it as a Plug-in, I have not allowed any updates to Chromium.  I did get your program running on windows using 32bit Foxpro which also still supports google earth plug in

**Comment by QIUWEIHAO** [comment]
Hi @gary-w-johnson ,

I am a researcher at UCSB. Could you send me the installation file of your Google Earth Plug-in? The installation for web plugin is removed now, though I did install the right version of Chromium.

Thanks,
Weihao

**Comment by mikeroberts3000** [comment]
@gary-w-johnson Actually if you have an installation file, can you please post it here?  :D

**Comment by gary-w-johnson** [comment]
File is almost 90MB, looks like 10MB is max.  Any ideas where I can put it , so you can get at it?

**Comment by QIUWEIHAO** [comment]
@gary-w-johnson  wonderful!! I will appreciate a lot if you share it somewhere and put the link on the homepage of this repository.

**Comment by mikeroberts3000** [comment]
@gary-w-johnson email me and I'll create an upload link for you.

**Comment by QIUWEIHAO** [comment]
@mikeroberts3000 did he upload?

**Comment by gary-w-johnson** [comment]
Hi Guys, sorry for the delay I'm retired and only check email off and on
throughout the day. Uploaded 2 files to Mike’s dropbox, ver 6 and 7, 7 is
the larger of the two and the one that has worked for me.  Per some reports
people have had better results with less problems using 6.

**Comment by mikeroberts3000** [comment]
@QIUWEIHAO I updated the readme with a download link for the chrome plugin. Give that a try, and please do post your findings here. Thanks to @gary-w-johnson for the links to the installer files.

**Comment by QIUWEIHAO** [comment]
Got it. Will try and post findings later.

**Comment by QIUWEIHAO** [comment]
Hi. I installed the plugin. The chromium still doesn't work. The plugin is not .crx file. It's a file to install a .plugin file onto the computer, which seems to be used for Safari. However, Safari doesn't work either.

I checked the API for Google Maps for Web, iOS and Android, and they all doesn't support the Google Earth API.
I also found in the app of Google Maps on mobile phones, google only supports 2D map and street view. However, on the web, people can see the 3D map by clicking a mode-shift button. I believe the API for Google Maps for Web will soon support the Google Earth API, but it's just unknown when.

The Google Maps API:
https://developers.google.com/maps/
https://developers.google.com/maps/web/

**Comment by mikeroberts3000** [comment]
Good to know. Thanks for posting the update. There's one more thing you can try. There is another installer in the same folder as the one you downloaded. You can navigate to it on GitHub. I'm in the car right now so I can't paste the link. This  other installer is actually the one Gary claims to use. I recommend giving this other installer a try before we give up.

**Comment by gary-w-johnson** [comment]
QIUWEIHAO i just uploaded the zip file of a copy of my plugin folder on my
Mac for Google Earth to Mike's Dropbox.  Not able to find the .crx file you
were talking about?

**Comment by QIUWEIHAO** [comment]
@gary-w-johnson I tried both installers, but it seems not going to work. The installer is creating a file name "Google Earth Web Plug-in.plugin". It's in the folder that holds the plugins for Safari. Usually the extensions program for Chrome or Chromium are with the suffix of crx.  

Are you sure that plugin is the only one that exists in your computer?
Is Horus still working on you computer?

**Comment by gary-w-johnson** [comment]
I apologize to everyone, just checked to see if program was still running
under Mas and PC.  Program is running with no errors but when I go to
LocalHost:5000 it never loads.  I checked the last time I made some code
changes and it was at the start of the month, looks like API support
stopped on the 11th of this month.


At this point in time no one seems to have a 3D workaround for the Google
Earth API, willing to take some time to see if I can find some options.
Think this is too good of a tool to let go of.

**Comment by QIUWEIHAO** [comment]
@mikeroberts3000  check this app out..https://developer.dji.com/showcase/6abe12d78efbce14d25daabf4e259508/  Pretty similar to your work. But the output is far worser than yours..

**Comment by mikeroberts3000** [comment]
@QIUWEIHAO Ah, thanks for the link. We actually know these guys. They were in the Stanford UAV Club at the time we were developing our app. I believe they were also using some of our code for a while. And, taking further inspiration from our work, their home page used to have the tower on the Stanford campus as their main demo example 😄

**Comment by QIUWEIHAO** [comment]
@mikeroberts3000 No wonder.... I found that they are using Apple Maps API.. Ironic.. It's a great idea! How do you think?

**Comment by mikeroberts3000** [comment]
@QIUWEIHAO Using the Apple Maps API? Yeah! I'd love to see a resurrected version of our app using Apple Maps as the backend. Of course my preference would be for a solution that works across all platforms. But currently Google Earth doesn't seem to work on any platforms 😄

**Comment by QIUWEIHAO** [comment]
@mikeroberts3000 One bad thing about the Apple Maps is that it has far less available 3D models than what Google Maps has... I think the 3d view are only available in the major cities.

**Comment by mikeroberts3000** [comment]
The Google Earth web plugin is finally deprecated, and Horus is currently not functional. So I'm closing this issue.
